#! /bin/sh
ghpages() {
    echo "deploying gh-pages"
    cd build && ~/.scripts/tools/gcap && cd ..
}

ctrlc() {
    echo "deploying to ctrl-c"
    sftp dhruva@ctrl-c.club <<EOF
put gemini/* public_gemini
exit 
EOF
}

case "$1" in
  ghpages) ghpages
  ;;
  ctrlc) ctrlc
  ;;
  *) ghpages && ctrlc
  ;;
esac

