#! /bin/sh
ghpages() {
    echo "deploying gh-pages"
    ./make html /blog
    gcap 
}

ctrlc() {
    echo "deploying to ctrl-c"
    ./make all /~dhruva
    rsync -ave ssh gemini ctrl-c.club:gemini
    rsync -ave ssh build ctrl-c.club:build
}

case "$1" in
  ghpages) ghpages
  ;;
  ctrlc) ctrlc
  ;;
  *) ctrlc && ghpages
  ;;
esac

