#!/bin/sh
DOMAIN="https://dhruvasambrani.github.io/newblog"
POST_DIR="."
AUTHOR="dhruvasambrani19@gmail.com (Dhruva Sambrani)"
TIME="00:00:00 IST"

echo "<rss version=\"2.0\" xmlns:atom=\"http://www.w3.org/2005/Atom\">
  <channel>
    <title>YOUR-BLOG-TITLE</title>
    <link>$DOMAIN</link>
    <description>Dhruva's Blog, a collectionf of thoughts, guides and random shit</description>
    <ttl>60</ttl>
    <atom:link href=\"$DOMAIN/feed.xml\" rel=\"self\" type=\"application/rss+xml\" />";

for file in $POST_DIR/20*.md; do
    dt=$(echo $file | sed -E "s/\.\/(.*)_.*/\1/g")
    echo "    <item>
        <pubDate>$(date -d "$dt" +"%d %m %Y") $TIME</pubDate>
        <title>$(head -n 2 $file | tail -n 1 | sed -E "s/title://g")</title>
        <link>$DOMAIN/$file</link>
        <description>$(tail -n +4 $file)</description>
        <author>$AUTHOR</author>
        <guid>$DOMAIN/$file</guid>
      </item>";
done

echo "  </channel>
</rss>";
